/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author resha
 */
import java.awt.Image;
import javax.swing.ImageIcon;
import java.util.*;

public class AboutUsFrame extends javax.swing.JFrame {
        
    private MainFrame mainFrame;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AboutUsFrame.class.getName());

    /**
     * Creates new form AddCharity
     */
    public AboutUsFrame(MainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        // Load and scale the image to fit the dimensions of the label
        ImageIcon image = new ImageIcon("C:\\Users\\resha\\OneDrive\\Desktop\\Documents\\NetBeansProjects\\CulminatingCopy\\charity.jpg");
        Image scaledImage = image.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
        lblImage.setIcon(new ImageIcon(scaledImage));
        
        txaContactUs.setText("Reshad Mohsin\nCoby Johns\nArujan Surendiran\nYuvraj Shahi\nThamil Ramathesun\n\nEmail: charityconnect@gmail.com");
        txaMission.setText("The mission of CharityConnect is to make it easier for people to discover and "
                + "support local charities across the Greater Toronto Area. Many organizations do important work in their communities, "
                + "but finding reliable and organized information about them can be frustrating and overwhelming. Instead of manually "
                + "searching the internet, through our application, users can quickly find charities that match what they are looking for"
                + "based on their interests, causes, and location."
                + " Overall, CharityConnect allows people to contribute to meaningful causes in their local community.");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReturn = new javax.swing.JButton();
        sprUnderline = new javax.swing.JSeparator();
        lblTitle = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblContactUs = new javax.swing.JLabel();
        scrTextScroll1 = new javax.swing.JScrollPane();
        txaContactUs = new javax.swing.JTextArea();
        lblMission = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        scrTextScroll2 = new javax.swing.JScrollPane();
        txaMission = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnReturn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReturn.setText("Return to Homepage");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Gill Sans MT", 1, 36)); // NOI18N
        lblTitle.setText("CharityConnect");

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblContactUs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContactUs.setText("Contributers - Contact Us");

        txaContactUs.setEditable(false);
        txaContactUs.setColumns(20);
        txaContactUs.setLineWrap(true);
        txaContactUs.setRows(5);
        txaContactUs.setWrapStyleWord(true);
        scrTextScroll1.setViewportView(txaContactUs);

        lblMission.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMission.setText("Our Mission:");

        txaMission.setColumns(20);
        txaMission.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txaMission.setLineWrap(true);
        txaMission.setRows(5);
        txaMission.setWrapStyleWord(true);
        scrTextScroll2.setViewportView(txaMission);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sprUnderline, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(lblMission)
                    .addComponent(scrTextScroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(scrTextScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnReturn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExit))
                            .addComponent(lblContactUs))
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnExit)
                    .addComponent(btnReturn))
                .addGap(3, 3, 3)
                .addComponent(sprUnderline, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMission)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblContactUs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(scrTextScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scrTextScroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        mainFrame.setLocationRelativeTo(null);
        mainFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0); // Exits the program
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel lblContactUs;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMission;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane scrTextScroll1;
    private javax.swing.JScrollPane scrTextScroll2;
    private javax.swing.JSeparator sprUnderline;
    private javax.swing.JTextArea txaContactUs;
    private javax.swing.JTextArea txaMission;
    // End of variables declaration//GEN-END:variables
}
