/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author resha
 */
import java.util.*;
import javax.swing.*;

public class MainFrame extends javax.swing.JFrame {
    
    ArrayList<Charity> charityList;
    CharityManager charityManager;
    UserManager userManager;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    
    public MainFrame(UserManager userManager, ArrayList<Charity> charityList) {
        initComponents();

        this.userManager = userManager;
        this.charityList = charityList;

        charityManager = new CharityManager(charityList);
       
        updateWelcomeLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearch = new javax.swing.JButton();
        lblDescription = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnAccountLogin = new javax.swing.JButton();
        txtInput = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        scrScroll = new javax.swing.JScrollPane();
        txaOutput = new javax.swing.JTextArea();
        cmbSearchBy = new javax.swing.JComboBox<>();
        lblSearchBy = new javax.swing.JLabel();
        sprUnderline = new javax.swing.JSeparator();
        lblCategories = new javax.swing.JLabel();
        cmbCategories = new javax.swing.JComboBox<>();
        btnAddCharity = new javax.swing.JButton();
        btnAboutUs = new javax.swing.JButton();
        lblStartCharity = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnAccountLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblDescription.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDescription.setText("Search for local charities in the GTA below:");

        lblTitle.setFont(new java.awt.Font("Gill Sans MT", 1, 36)); // NOI18N
        lblTitle.setText("CharityConnect");

        btnAccountLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAccountLogin.setText("Login");
        btnAccountLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountLoginActionPerformed(evt);
            }
        });

        txtInput.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtInput.setText("Enter Here");
        txtInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtInputMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtInputMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtInputMousePressed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txaOutput.setEditable(false);
        txaOutput.setColumns(20);
        txaOutput.setRows(5);
        scrScroll.setViewportView(txaOutput);

        cmbSearchBy.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cmbSearchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "City", "Charity Name" }));

        lblSearchBy.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSearchBy.setText("Search By:");

        lblCategories.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblCategories.setText("Categories:");

        cmbCategories.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cmbCategories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Hunger/Poverty", "Education", "Animals", "Housing", "Health", "Social Services" }));

        btnAddCharity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddCharity.setText("Add Charity");
        btnAddCharity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCharityActionPerformed(evt);
            }
        });

        btnAboutUs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAboutUs.setText("About Us");
        btnAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutUsActionPerformed(evt);
            }
        });

        lblStartCharity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStartCharity.setText("Looking to start a charity?");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnAccountLogOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAccountLogOut.setText("Log Out");
        btnAccountLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scrScroll, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDescription)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblSearchBy)
                                            .addGap(18, 18, 18)
                                            .addComponent(cmbSearchBy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblCategories)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cmbCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnAddCharity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblStartCharity))
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sprUnderline, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAboutUs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAccountLogin)
                        .addGap(10, 10, 10)
                        .addComponent(btnAccountLogOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnExit)
                    .addComponent(btnAccountLogin)
                    .addComponent(btnAccountLogOut)
                    .addComponent(btnAboutUs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sprUnderline, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescription))
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbSearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSearchBy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategories)
                            .addComponent(cmbCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStartCharity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddCharity)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountLoginActionPerformed
        LoginFrame login = new LoginFrame(userManager, charityList);
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.dispose(); // CLOSE MainFrame
    }//GEN-LAST:event_btnAccountLoginActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0); // Exits the program
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtInputMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInputMouseEntered
        if (txtInput.getText().isBlank() || txtInput.getText().equals("Enter Here")) {
            txtInput.setText("...");
        }
    }//GEN-LAST:event_txtInputMouseEntered

    private void txtInputMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInputMouseExited
        if (txtInput.getText().isBlank() || txtInput.getText().equals("...")) {
            txtInput.setText("Enter Here");
        }
    }//GEN-LAST:event_txtInputMouseExited

    private void btnAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutUsActionPerformed
        AboutUsFrame about = new AboutUsFrame(userManager, charityList);
        about.setLocationRelativeTo(null);
        about.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnAboutUsActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        txaOutput.setText("");
        String keyword = txtInput.getText().trim();
        String searchBy = cmbSearchBy.getSelectedItem().toString();
        String category = cmbCategories.getSelectedItem().toString();

        if (keyword.isEmpty() | keyword.equals("...") | keyword.equals("Enter Here")) {
            JOptionPane.showMessageDialog(this, "Please enter a search term.");
            return;
        }

        ArrayList<Charity> results = charityManager.search(keyword, searchBy, category);

        if (results.isEmpty()) {
            txaOutput.setText("No charities found.");
            return;
        }

        StringBuilder sb = new StringBuilder();
        charityManager.displayResults(results, 0, sb);

        txaOutput.setText(sb.toString());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddCharityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCharityActionPerformed
        if (userManager == null) {
            JOptionPane.showMessageDialog(this, "You must be logged in to add a charity.");
            return;
        } else if (!userManager.isLoggedIn()) {
            JOptionPane.showMessageDialog(this, "You must be logged in to add a charity.");
            return;
        }

        AddCharityFrame add = new AddCharityFrame(userManager, charityList);
        add.setLocationRelativeTo(null);
        add.setVisible(true);
        this.dispose(); // CLOSE MainFrame
    }//GEN-LAST:event_btnAddCharityActionPerformed

    private void btnAccountLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountLogOutActionPerformed
        txaOutput.setText("");
        if (userManager == null) {
            JOptionPane.showMessageDialog(this, "You are not logged in.");
            return;
        } else if (!userManager.isLoggedIn()) {
            JOptionPane.showMessageDialog(this, "You are not logged in.");
            return;
        }

        userManager.logout();
        updateWelcomeLabel();

        JOptionPane.showMessageDialog(this, "You have been logged out.");
    }//GEN-LAST:event_btnAccountLogOutActionPerformed

    private void txtInputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInputMousePressed
        if (txtInput.getText().equals("..."))  {
            txtInput.setText("");
        }
    }//GEN-LAST:event_txtInputMousePressed
    
    private void updateWelcomeLabel() {
        if (userManager == null) {
            lblName.setText("Welcome Guest");
        } else if (!userManager.isLoggedIn()) {
            lblName.setText("Welcome Guest");
        } else {
            String firstName = userManager.getCurrentUser().getFirstName();
            lblName.setText("Welcome " + firstName);
        }
    }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        ArrayList<Charity> charities = CharityFileHandler.loadCharities("GTA_Charities_Database.txt");
        CharitySorter.sortByName(charities);
        UserManager userManager = new UserManager(UserFileHandler.loadUsers("users.txt"));
        
        MainFrame main = new MainFrame(userManager, charities);
        main.setLocationRelativeTo(null); 
        main.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutUs;
    private javax.swing.JButton btnAccountLogOut;
    private javax.swing.JButton btnAccountLogin;
    private javax.swing.JButton btnAddCharity;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbCategories;
    private javax.swing.JComboBox<String> cmbSearchBy;
    private javax.swing.JLabel lblCategories;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSearchBy;
    private javax.swing.JLabel lblStartCharity;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane scrScroll;
    private javax.swing.JSeparator sprUnderline;
    private javax.swing.JTextArea txaOutput;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
